### ISSUE TITLE
Various Issues/Feature Requests

### ISSUE THREAD

**Issue by fluury** [DarkDes/AsepriteSpriteStackEd#1]
First of all, thank you so much for creating this! I've been using Spritepile for Spritestacking, and man it is painful sometimes. Finally getting to just use Aseprite is amazing. I have a few Issues/Feature Requests though. I am 100% clueless when it comes to Aseprite and its architecture, so please pardon if some of this seems unachievable/ignorant or something.

**Feature Requests**

Overall, I'd love if the Preview window could be a bit more dynamic, similar to the one of [Spritepile](https://store.steampowered.com/app/1098420/SpritePile/). While the software lacks a lot of other stuff, they really nailed that aspect of it. This includes:

- M2 (Right click) + drag to change offset of preview sprite
- A less restrictive zoom (even better if activated via. Mousewheel)
- Adjustable Preview Window size (Spritepile lacks this feature, but it would be awesome for more detailed models)
- Adjustable Rotation speed

**Issues**

Other than that, I have also run into a few issues/Questions:
I'm on Aseprite v1.3-rc6x64.

- Auto-Repaint doesn't seem to work? Checked it, nothing is happening when drawing stuff. Not reacting to new pixels drawn, removed, bucket painted, whatever.
- What is the difference between "Repaint" and "Update" anyways?
- Rotation anim seems model complexity depedant. A bit jarring when small models rotate at super fast speeds.
- Poor performance on particularly large models. I'm assuming this is a limitation of Aseprite Scripting, but I figured I'd throw it out regardless.

Again, thanks so much for having done this! I'm working on [a game](https://store.steampowered.com/app/2454350/REDLINE_CROOKS/) that uses spritestacking for the 3D models and this will make my workflow so much quicker.

**Comment by DarkDes** [comment]
Hi, glad you found this script useful!

The difference between "Repaint" and "Update" is that Repaint redraws the current frame, while Update also recalculates the parameters (it may be slower, but it is more accurate). These functions aren't really needed that much.

Regarding your requests for new features - I will try to implement them. Thanks!

To be honest this is my first Aseprite and LUA script. But as far as I can understand, the performance issues are really from Aseprite Scripting. If there was an implementation in the Aseprite API for sprite rotation, it would be much faster. HOWEVER! Thanks to the wonderful @KarlTheCool now "auto-repaint" has a significant performance boost (but there are "artefacts" if you rotate the model quickly).

Your game looks really cool!
(I apologise for replying so late)
